// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_qutes_termines = "CgkI796-sI4JEAIQFg"; // <GPGSID>
        public const string leaderboard_nombre_de_parties_joues = "CgkI796-sI4JEAIQEg"; // <GPGSID>
        public const string leaderboard_meilleur_score_mode_infini = "CgkI796-sI4JEAIQEA"; // <GPGSID>
        public const string leaderboard_plus_haut_niveau_mode_campagne = "CgkI796-sI4JEAIQEQ"; // <GPGSID>
        public const string leaderboard_argent_maximum = "CgkI796-sI4JEAIQEw"; // <GPGSID>

}

